// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LEARNING_ANGULAR_JS.Controllers
{
	public partial class HomeController
	{
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected HomeController(Dummy d) { }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(ActionResult result)
		{
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoute(callInfo.RouteValueDictionary);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
		{
			return RedirectToAction(taskResult.Result);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
		{
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
		{
			return RedirectToActionPermanent(taskResult.Result);
		}

		[NonAction]
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public virtual System.Web.Mvc.JsonResult SetData1000()
		{
			return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetData1000);
		}
		[NonAction]
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public virtual System.Web.Mvc.JsonResult SetData1010()
		{
			return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetData1010);
		}
		[NonAction]
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public virtual System.Web.Mvc.JsonResult Delete1000()
		{
			return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Delete1000);
		}
		[NonAction]
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public virtual System.Web.Mvc.JsonResult GetData1020()
		{
			return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetData1020);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public HomeController Actions { get { return MVC.Home; } }
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Area = "";
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Name = "Home";
		[GeneratedCode("T4MVC", "2.0")]
		public const string NameConst = "Home";
		[GeneratedCode("T4MVC", "2.0")]
		static readonly ActionNamesClass s_actions = new ActionNamesClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionNamesClass ActionNames { get { return s_actions; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNamesClass
		{
			public readonly string Index = "Index";
			public readonly string Learn1000 = "Learn1000";
			public readonly string Learn1010 = "Learn1010";
			public readonly string GetData1000 = "GetData1000";
			public readonly string Learn1020 = "Learn1020";
			public readonly string Learn1030 = "Learn1030";
			public readonly string Learn1035 = "Learn1035";
			public readonly string GetData1010 = "GetData1010";
			public readonly string Learn1040 = "Learn1040";
			public readonly string Learn1050 = "Learn1050";
			public readonly string SetData1000 = "SetData1000";
			public readonly string Learn1060 = "Learn1060";
			public readonly string SetData1010 = "SetData1010";
			public readonly string Delete1000 = "Delete1000";
			public readonly string Learn1070 = "Learn1070";
			public readonly string GetData1020 = "GetData1020";
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNameConstants
		{
			public const string Index = "Index";
			public const string Learn1000 = "Learn1000";
			public const string Learn1010 = "Learn1010";
			public const string GetData1000 = "GetData1000";
			public const string Learn1020 = "Learn1020";
			public const string Learn1030 = "Learn1030";
			public const string Learn1035 = "Learn1035";
			public const string GetData1010 = "GetData1010";
			public const string Learn1040 = "Learn1040";
			public const string Learn1050 = "Learn1050";
			public const string SetData1000 = "SetData1000";
			public const string Learn1060 = "Learn1060";
			public const string SetData1010 = "SetData1010";
			public const string Delete1000 = "Delete1000";
			public const string Learn1070 = "Learn1070";
			public const string GetData1020 = "GetData1020";
		}


		static readonly ActionParamsClass_SetData1000 s_params_SetData1000 = new ActionParamsClass_SetData1000();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionParamsClass_SetData1000 SetData1000Params { get { return s_params_SetData1000; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionParamsClass_SetData1000
		{
			public readonly string person = "person";
		}
		static readonly ActionParamsClass_SetData1010 s_params_SetData1010 = new ActionParamsClass_SetData1010();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionParamsClass_SetData1010 SetData1010Params { get { return s_params_SetData1010; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionParamsClass_SetData1010
		{
			public readonly string person = "person";
		}
		static readonly ActionParamsClass_Delete1000 s_params_Delete1000 = new ActionParamsClass_Delete1000();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionParamsClass_Delete1000 Delete1000Params { get { return s_params_Delete1000; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionParamsClass_Delete1000
		{
			public readonly string id = "id";
		}
		static readonly ActionParamsClass_GetData1020 s_params_GetData1020 = new ActionParamsClass_GetData1020();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionParamsClass_GetData1020 GetData1020Params { get { return s_params_GetData1020; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionParamsClass_GetData1020
		{
			public readonly string id = "id";
		}
		static readonly ViewsClass s_views = new ViewsClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ViewsClass Views { get { return s_views; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ViewsClass
		{
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Learn1000 = "Learn1000";
                public readonly string Learn1010 = "Learn1010";
                public readonly string Learn1020 = "Learn1020";
                public readonly string Learn1030 = "Learn1030";
                public readonly string Learn1035 = "Learn1035";
                public readonly string Learn1040 = "Learn1040";
                public readonly string Learn1050 = "Learn1050";
                public readonly string Learn1060 = "Learn1060";
                public readonly string Learn1070 = "Learn1070";
            }
            public readonly string Index = "~/Views/Home/Index.cshtml";
            public readonly string Learn1000 = "~/Views/Home/Learn1000.cshtml";
            public readonly string Learn1010 = "~/Views/Home/Learn1010.cshtml";
            public readonly string Learn1020 = "~/Views/Home/Learn1020.cshtml";
            public readonly string Learn1030 = "~/Views/Home/Learn1030.cshtml";
            public readonly string Learn1035 = "~/Views/Home/Learn1035.cshtml";
            public readonly string Learn1040 = "~/Views/Home/Learn1040.cshtml";
            public readonly string Learn1050 = "~/Views/Home/Learn1050.cshtml";
            public readonly string Learn1060 = "~/Views/Home/Learn1060.cshtml";
            public readonly string Learn1070 = "~/Views/Home/Learn1070.cshtml";
		}
	}

	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public partial class T4MVC_HomeController : LEARNING_ANGULAR_JS.Controllers.HomeController
	{
		public T4MVC_HomeController() : base(Dummy.Instance) { }

		[NonAction]
		partial void IndexOverride(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Index()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Index);
			IndexOverride(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1000Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1000()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1000);
			Learn1000Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1010Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1010()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1010);
			Learn1010Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void GetData1000Override(T4MVC_System_Web_Mvc_JsonResult callInfo);

		[NonAction]
		public override System.Web.Mvc.JsonResult GetData1000()
		{
			var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetData1000);
			GetData1000Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1020Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1020()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1020);
			Learn1020Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1030Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1030()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1030);
			Learn1030Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1035Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1035()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1035);
			Learn1035Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void GetData1010Override(T4MVC_System_Web_Mvc_JsonResult callInfo);

		[NonAction]
		public override System.Web.Mvc.JsonResult GetData1010()
		{
			var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetData1010);
			GetData1010Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1040Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1040()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1040);
			Learn1040Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1050Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1050()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1050);
			Learn1050Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void SetData1000Override(T4MVC_System_Web_Mvc_JsonResult callInfo, Models.Person person);

		[NonAction]
		public override System.Web.Mvc.JsonResult SetData1000(Models.Person person)
		{
			var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetData1000);
			ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "person", person);
			SetData1000Override(callInfo, person);
			return callInfo;
		}

		[NonAction]
		partial void Learn1060Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1060()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1060);
			Learn1060Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void SetData1010Override(T4MVC_System_Web_Mvc_JsonResult callInfo, Models.Person person);

		[NonAction]
		public override System.Web.Mvc.JsonResult SetData1010(Models.Person person)
		{
			var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetData1010);
			ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "person", person);
			SetData1010Override(callInfo, person);
			return callInfo;
		}

		[NonAction]
		partial void Delete1000Override(T4MVC_System_Web_Mvc_JsonResult callInfo, System.Guid id);

		[NonAction]
		public override System.Web.Mvc.JsonResult Delete1000(System.Guid id)
		{
			var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Delete1000);
			ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
			Delete1000Override(callInfo, id);
			return callInfo;
		}

		[NonAction]
		partial void Learn1070Override(T4MVC_System_Web_Mvc_ViewResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ViewResult Learn1070()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.Learn1070);
			Learn1070Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void GetData1020Override(T4MVC_System_Web_Mvc_JsonResult callInfo, int id);

		[NonAction]
		public override System.Web.Mvc.JsonResult GetData1020(int id)
		{
			var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.GetData1020);
			ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
			GetData1020Override(callInfo, id);
			return callInfo;
		}

	}
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
