// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace LEARNING_ANGULAR_JS.Controllers
{
	public partial class LearningValidationController
	{
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected LearningValidationController(Dummy d) { }

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(ActionResult result)
		{
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoute(callInfo.RouteValueDictionary);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
		{
			return RedirectToAction(taskResult.Result);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
		{
			var callInfo = result.GetT4MVCResult();
			return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
		{
			return RedirectToActionPermanent(taskResult.Result);
		}


		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public LearningValidationController Actions { get { return MVC.LearningValidation; } }
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Area = "";
		[GeneratedCode("T4MVC", "2.0")]
		public readonly string Name = "LearningValidation";
		[GeneratedCode("T4MVC", "2.0")]
		public const string NameConst = "LearningValidation";
		[GeneratedCode("T4MVC", "2.0")]
		static readonly ActionNamesClass s_actions = new ActionNamesClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionNamesClass ActionNames { get { return s_actions; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNamesClass
		{
			public readonly string Learn0100 = "Learn0100";
			public readonly string Learn0200 = "Learn0200";
			public readonly string Learn0300 = "Learn0300";
			public readonly string Learn0400 = "Learn0400";
			public readonly string Learn0500 = "Learn0500";
			public readonly string Learn0600 = "Learn0600";
			public readonly string Learn0700 = "Learn0700";
			public readonly string Learn0800 = "Learn0800";
			public readonly string Learn0900 = "Learn0900";
			public readonly string Learn1000 = "Learn1000";
			public readonly string Learn1010 = "Learn1010";
			public readonly string Learn1020 = "Learn1020";
			public readonly string Learn1030 = "Learn1030";
			public readonly string Learn1040 = "Learn1040";
			public readonly string Learn1050 = "Learn1050";
			public readonly string Learn1060 = "Learn1060";
			public readonly string Learn10700 = "Learn10700";
			public readonly string Learn1080 = "Learn1080";
			public readonly string Learn1090 = "Learn1090";
			public readonly string Learn1100 = "Learn1100";
			public readonly string Learn1200 = "Learn1200";
			public readonly string Test = "Test";
		}

		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionNameConstants
		{
			public const string Learn0100 = "Learn0100";
			public const string Learn0200 = "Learn0200";
			public const string Learn0300 = "Learn0300";
			public const string Learn0400 = "Learn0400";
			public const string Learn0500 = "Learn0500";
			public const string Learn0600 = "Learn0600";
			public const string Learn0700 = "Learn0700";
			public const string Learn0800 = "Learn0800";
			public const string Learn0900 = "Learn0900";
			public const string Learn1000 = "Learn1000";
			public const string Learn1010 = "Learn1010";
			public const string Learn1020 = "Learn1020";
			public const string Learn1030 = "Learn1030";
			public const string Learn1040 = "Learn1040";
			public const string Learn1050 = "Learn1050";
			public const string Learn1060 = "Learn1060";
			public const string Learn10700 = "Learn10700";
			public const string Learn1080 = "Learn1080";
			public const string Learn1090 = "Learn1090";
			public const string Learn1100 = "Learn1100";
			public const string Learn1200 = "Learn1200";
			public const string Test = "Test";
		}


		static readonly ActionParamsClass_Learn1200 s_params_Learn1200 = new ActionParamsClass_Learn1200();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ActionParamsClass_Learn1200 Learn1200Params { get { return s_params_Learn1200; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ActionParamsClass_Learn1200
		{
			public readonly string username = "username";
		}
		static readonly ViewsClass s_views = new ViewsClass();
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public ViewsClass Views { get { return s_views; } }
		[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
		public class ViewsClass
		{
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Learn0100 = "Learn0100";
                public readonly string Learn0200 = "Learn0200";
                public readonly string Learn0300 = "Learn0300";
                public readonly string Learn0400 = "Learn0400";
                public readonly string Learn0500 = "Learn0500";
                public readonly string Learn0600 = "Learn0600";
                public readonly string Learn0700 = "Learn0700";
                public readonly string Learn0800 = "Learn0800";
                public readonly string Learn0900 = "Learn0900";
                public readonly string Learn1000 = "Learn1000";
                public readonly string Learn10000 = "Learn10000";
                public readonly string Learn10100 = "Learn10100";
                public readonly string Learn10200 = "Learn10200";
                public readonly string Learn10600 = "Learn10600";
                public readonly string Learn10700 = "Learn10700";
                public readonly string Learn10800 = "Learn10800";
                public readonly string Learn10900 = "Learn10900";
                public readonly string Learn11000 = "Learn11000";
                public readonly string Learn12000 = "Learn12000";
                public readonly string Test = "Test";
            }
            public readonly string Learn0100 = "~/Views/LearningValidation/Learn0100.cshtml";
            public readonly string Learn0200 = "~/Views/LearningValidation/Learn0200.cshtml";
            public readonly string Learn0300 = "~/Views/LearningValidation/Learn0300.cshtml";
            public readonly string Learn0400 = "~/Views/LearningValidation/Learn0400.cshtml";
            public readonly string Learn0500 = "~/Views/LearningValidation/Learn0500.cshtml";
            public readonly string Learn0600 = "~/Views/LearningValidation/Learn0600.cshtml";
            public readonly string Learn0700 = "~/Views/LearningValidation/Learn0700.cshtml";
            public readonly string Learn0800 = "~/Views/LearningValidation/Learn0800.cshtml";
            public readonly string Learn0900 = "~/Views/LearningValidation/Learn0900.cshtml";
            public readonly string Learn1000 = "~/Views/LearningValidation/Learn1000.cshtml";
            public readonly string Learn10000 = "~/Views/LearningValidation/Learn10000.cshtml";
            public readonly string Learn10100 = "~/Views/LearningValidation/Learn10100.cshtml";
            public readonly string Learn10200 = "~/Views/LearningValidation/Learn10200.cshtml";
            public readonly string Learn10600 = "~/Views/LearningValidation/Learn10600.cshtml";
            public readonly string Learn10700 = "~/Views/LearningValidation/Learn10700.cshtml";
            public readonly string Learn10800 = "~/Views/LearningValidation/Learn10800.cshtml";
            public readonly string Learn10900 = "~/Views/LearningValidation/Learn10900.cshtml";
            public readonly string Learn11000 = "~/Views/LearningValidation/Learn11000.cshtml";
            public readonly string Learn12000 = "~/Views/LearningValidation/Learn12000.cshtml";
            public readonly string Test = "~/Views/LearningValidation/Test.cshtml";
		}
	}

	[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
	public partial class T4MVC_LearningValidationController : LEARNING_ANGULAR_JS.Controllers.LearningValidationController
	{
		public T4MVC_LearningValidationController() : base(Dummy.Instance) { }

		[NonAction]
		partial void Learn0100Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0100()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0100);
			Learn0100Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn0200Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0200()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0200);
			Learn0200Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn0300Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0300()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0300);
			Learn0300Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn0400Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0400()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0400);
			Learn0400Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn0500Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0500()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0500);
			Learn0500Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn0600Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0600()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0600);
			Learn0600Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn0700Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0700()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0700);
			Learn0700Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn0800Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0800()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0800);
			Learn0800Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn0900Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn0900()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn0900);
			Learn0900Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1000Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1000()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1000);
			Learn1000Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1010Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1010()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1010);
			Learn1010Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1020Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1020()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1020);
			Learn1020Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1030Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1030()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1030);
			Learn1030Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1040Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1040()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1040);
			Learn1040Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1050Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1050()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1050);
			Learn1050Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1060Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1060()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1060);
			Learn1060Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn10700Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn10700()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn10700);
			Learn10700Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1080Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1080()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1080);
			Learn1080Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1090Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1090()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1090);
			Learn1090Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1100Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1100()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1100);
			Learn1100Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1200Override(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1200()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1200);
			Learn1200Override(callInfo);
			return callInfo;
		}

		[NonAction]
		partial void Learn1200Override(T4MVC_System_Web_Mvc_ActionResult callInfo, string username);

		[NonAction]
		public override System.Web.Mvc.ActionResult Learn1200(string username)
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Learn1200);
			ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "username", username);
			Learn1200Override(callInfo, username);
			return callInfo;
		}

		[NonAction]
		partial void TestOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

		[NonAction]
		public override System.Web.Mvc.ActionResult Test()
		{
			var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Test);
			TestOverride(callInfo);
			return callInfo;
		}

	}
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
